sudo: required
language: go
go:
- '1.14'
env:
  global:
    secure: t2wuL9Afv6s/fClhmRxhG0ztlHhTKYo7qnTjQCdlf/oI+8N2MQsCzUPy/a+sQ03lS8Lo9u1b3Z05MAiXs22VWmZUfGP+n2kg15G9B/1LKzDixEN8LBE2nuctHZizI+NeStrhF6C4CBgD9/rE5xtZb1etV+g4Ze4phXPcK7ZgOm7coiJH36MajiArHAXS92w275xPhFBrq+3H9DlRnxGlfKKI3aGgEjxKNLLHrlnTYTjLiAmGMrex2Pq6ac7HRJ29y/3ASext01soZAttKkpmEaQId+S/uFfoi78lVSlWLjH3BcWtoCZI1gmKdtyxaSwTA+p2LWpWAnJSkrNfqVixT6WYv3ud7tkYR3vzQw5irlptmUCl0G6WiVyKOFhZbp56OhIqKuOzoHnkvFTp9ILoYMEX5CXFfJ7sUWUwM01JFNiPijQLqySl1wPEVA1DdL/+8vWGRPNaDNwilPlDa0CRVoziIe81Xrs9P1Sc3rWgLnC4MkXZ5MoOM/qIWPXDQ7WMOZfck2zye+nTe5BzOuYlWLqCyvK+xm4A7+0u+vMu8eO+xkJ/NllJ2/BoNfEoj7xzc/Nj58MEfEylEJnpQ+KCj5tFaYq39Q1KZ3fRA4C/El7MsPrNHOdwnOW7pYJ2+suJ55HTL1QtToz5lXt7QpbvxwiS6yNSOahbb8AU+YO1bCQ=
services:
- docker
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- make release