sudo: required
language: go
go:
- '1.14'
env:
  global:
  - DOCKER_USERNAME=nmetz
  - secure: t2wuL9Afv6s/fClhmRxhG0ztlHhTKYo7qnTjQCdlf/oI+8N2MQsCzUPy/a+sQ03lS8Lo9u1b3Z05MAiXs22VWmZUfGP+n2kg15G9B/1LKzDixEN8LBE2nuctHZizI+NeStrhF6C4CBgD9/rE5xtZb1etV+g4Ze4phXPcK7ZgOm7coiJH36MajiArHAXS92w275xPhFBrq+3H9DlRnxGlfKKI3aGgEjxKNLLHrlnTYTjLiAmGMrex2Pq6ac7HRJ29y/3ASext01soZAttKkpmEaQId+S/uFfoi78lVSlWLjH3BcWtoCZI1gmKdtyxaSwTA+p2LWpWAnJSkrNfqVixT6WYv3ud7tkYR3vzQw5irlptmUCl0G6WiVyKOFhZbp56OhIqKuOzoHnkvFTp9ILoYMEX5CXFfJ7sUWUwM01JFNiPijQLqySl1wPEVA1DdL/+8vWGRPNaDNwilPlDa0CRVoziIe81Xrs9P1Sc3rWgLnC4MkXZ5MoOM/qIWPXDQ7WMOZfck2zye+nTe5BzOuYlWLqCyvK+xm4A7+0u+vMu8eO+xkJ/NllJ2/BoNfEoj7xzc/Nj58MEfEylEJnpQ+KCj5tFaYq39Q1KZ3fRA4C/El7MsPrNHOdwnOW7pYJ2+suJ55HTL1QtToz5lXt7QpbvxwiS6yNSOahbb8AU+YO1bCQ=
  - secure: OdOPoonz+zZ/DewkWtaGJK+SucUBCEbFDNAvS95kPqvbhPvQAPNQl+uDaEHp2Z6mwEJ53lsV64jPTDtIEBJ+LlSXzCkvjK7WPzZZMR7jMnntiw2DJCUPEYZMyQXuVDPm+5L+1aO1LanjywozIoRtzbv3fn9+/uEVObs0kBK9qZ3QnAYQZWpoV8m0ZCleK66efHzsoIS1trNaDzu6GyeTDjz9uertT73ZKdVrgs7lgIgGnA48ggrLDlG4299rCk9pRUwHCFSI12ikHDEjLtuYaxC6FyDD0zifjjgp4lXJDfWfDL3SrBnWgfxLWrytqfv/hPrA7kHDDPilJSbtrD3GzzDCBQ83Fhvt1NxHcWCQmaXOHKJBMJ8unBg8dFrlKmCaJlUcUnPQ8uVvn0+QF70RD41aq69KzzvU+wsYAIIkV7B7mzWjP5a3SM+MMToaa7I+8edhzz7xgdX0gaPUDZHjswhGaR3spY++dnrhcHEeRGInHTgmovAj0rINuAMi6SgFIWCQ8Oc8AUNoGvaB+LeJNXvxv+cPrxY+wjlD3xpA2S5hiN72mB7ULVTRkvPluHqHMqHyxZIYOgR8jvfh7KD3SZBZKL7h1/VUBmWG28NnVZ24HuSNKz0RsvxwnzHBvcipVV4WOuZav6KCkyvfoZsn4m6hYqI6M5H9/LFjoiwy84k=
services:
- docker
before_install:
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
script:
- make release
